/* Generado por importar_premat.py desde "Principios Movimiento y Posiciones.xlsx".
   No editar a mano: corregí la planilla y volvé a correr el script. */
const PREMAT = [
 {
  "id": "pm001",
  "n": "Diaphragmatic Breathing",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Respiración",
  "obj": "Mejorar respiración diafragmática",
  "reps": "5–8 respiraciones",
  "musculos": "Diafragma",
  "cadena": "Cadena profunda anterior",
  "plano": "Multiplanar",
  "contra": "EPOC agudo, dolor costal",
  "obs": "Expandir costillas inferiores.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "acostada_respira"
 },
 {
  "id": "pm002",
  "n": "Lateral Breathing",
  "pos": "Sedente",
  "principio": "Integración del tronco",
  "comp": "Respiración",
  "obj": "Respiración costal lateral",
  "reps": "5–10 respiraciones",
  "musculos": "Diafragma, intercostales",
  "cadena": "Cadena profunda anterior",
  "plano": "Multiplanar",
  "contra": "Dolor costal agudo",
  "obs": "Abdomen activo.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm003",
  "n": "Pulmonary Breathing",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Respiración",
  "obj": "Función pulmonar",
  "reps": "5–8 respiraciones",
  "musculos": "Diafragma, intercostales",
  "cadena": "Cadena profunda anterior",
  "plano": "Multiplanar",
  "contra": "Insuficiencia respiratoria aguda",
  "obs": "Respiración amplia y fluida.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "acostada_respira"
 },
 {
  "id": "pm004",
  "n": "Supported Neutral Spine",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Pelvis neutra",
  "obj": "Alineación espinal y pélvica",
  "reps": "6–10 repeticiones o mantener 5 respiraciones",
  "musculos": "Transverso abdominal, multífidos",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo",
  "obs": "Mantener pelvis neutra.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "fotoDudosa": "La foto muestra a alguien sentado, pero el ejercicio figura en supino."
 },
 {
  "id": "pm005",
  "n": "Pelvic Clock",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Control lumbopélvico",
  "reps": "1–2 vueltas completas en cada dirección (8–12 movimientos)",
  "musculos": "Transverso abdominal, oblicuos, multífidos",
  "cadena": "Cadena profunda anterior",
  "plano": "Multiplanar",
  "contra": "Dolor lumbar agudo",
  "obs": "Movimiento segmentado.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm006",
  "n": "Fingertip Abdominals",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Core profundo",
  "reps": "8–10 repeticiones",
  "musculos": "Transverso abdominal, recto abdominal, oblicuos",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor cervical agudo",
  "obs": "Activar el centro.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "acostada_respira"
 },
 {
  "id": "pm007",
  "n": "Pelvic Floor Activation",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Piso pélvico / estabilización",
  "reps": "5–10 respiraciones o 8–10 contracciones suaves",
  "musculos": "Piso pélvico, transverso abdominal",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor pélvico agudo",
  "obs": "No contraer glúteos.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm008",
  "n": "All Four Abdominals",
  "pos": "4 puntos",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Core global",
  "reps": "8–10 repeticiones",
  "musculos": "Transverso abdominal, oblicuos",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor de muñecas",
  "obs": "Columna neutra.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "cuadrupedia_brazo_pierna"
 },
 {
  "id": "pm009",
  "n": "Low Back Bridge",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Aumentar estabilidad de la espina dorsal",
  "reps": "8–10 repeticiones",
  "musculos": "Glúteo mayor, isquiotibiales, erectores espinales",
  "cadena": "Cadena posterior superficial",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo",
  "obs": "Subir vértebra por vértebra.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "puente"
 },
 {
  "id": "pm010",
  "n": "Standing Multifidi Engagement",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Mejorar estabilidad espinal",
  "reps": "8–10 repeticiones o mantener 5 respiraciones",
  "musculos": "Multífidos, transverso abdominal",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo",
  "obs": "Postura estable.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm011",
  "n": "Squats",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Patrón funcional de sentadilla",
  "reps": "8–12 repeticiones",
  "musculos": "Glúteos, cuádriceps, isquiotibiales",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor de rodilla, lesión aguda de cadera",
  "obs": "Rodillas alineadas.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm012",
  "n": "Single Leg Multifidi",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Mejorar estabilidad unilateral",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Multífidos, glúteo medio, transverso abdominal",
  "cadena": "Cadena estabilizadora del centro",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo, alteración del equilibrio",
  "obs": "Pelvis estable.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm013",
  "n": "Neutral Squats",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Mantener pelvis y columna neutra durante movimiento",
  "reps": "8–12 repeticiones",
  "musculos": "Glúteos, cuádriceps, transverso abdominal",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor de rodilla, lesión lumbar aguda",
  "obs": "Columna neutra.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm014",
  "n": "Knee Bend Variation",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Unidad interna",
  "obj": "Controlar alineación durante flexión de rodillas",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Cuádriceps, glúteos, transverso abdominal",
  "cadena": "Cadena anterior",
  "plano": "Sagital",
  "contra": "Dolor de rodilla, lesión de menisco",
  "obs": "Rodilla sobre el segundo dedo.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "plie"
 },
 {
  "id": "pm015",
  "n": "Marching",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "Control lumbopélvico",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Transverso abdominal, oblicuos, psoas",
  "cadena": "Cadena estabilizadora del centro",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo",
  "obs": "Evitar movimiento pélvico.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "marcha_supina"
 },
 {
  "id": "pm016",
  "n": "Toe Taps",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Unidad externa",
  "obj": "",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Transverso abdominal, oblicuos, psoas",
  "cadena": "Cadena estabilizadora del centro",
  "plano": "Sagital",
  "contra": "Hernia lumbar aguda",
  "obs": "Costillas conectadas.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm017",
  "n": "Diagonal Press",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Unidad externa (SOA-SOP)",
  "obj": "",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Oblicuos, transverso abdominal, glúteos",
  "cadena": "Cadena cruzada",
  "plano": "Transversal",
  "contra": "Dolor lumbar agudo, embarazo avanzado",
  "obs": "Presión cruzada, pelvis estable.",
  "libro": "Pre-MAT",
  "orig": "Deagobal Press",
  "fotos": 1
 },
 {
  "id": "pm018",
  "n": "Dead Bug",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "Estabilidad Lumbopélvica",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Transverso abdominal, oblicuos, multífidos",
  "cadena": "Cadena estabilizadora del centro",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo",
  "obs": "Zona lumbar estable.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm019",
  "n": "Bridge with Marching",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "1-Estabilidad Lumbopélvica 2-Fortalecer los isquiotibiales y glúteos",
  "reps": "6–8 repeticiones por lado",
  "musculos": "Glúteo mayor, isquiotibiales, erectores espinales",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de isquiotibiales",
  "obs": "Mantener altura del puente.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "puente"
 },
 {
  "id": "pm020",
  "n": "Swimming prep — single arm lift",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica + Unidad externa",
  "obj": "1-Estabilidad Lumbopelvica 2- Unidad Externa SOP",
  "reps": "8–10 repeticiones por lado",
  "musculos": "Erectores espinales, multífidos, deltoides posterior",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de hombro",
  "obs": "No rotar el tronco.",
  "libro": "Pre-MAT",
  "orig": "Swiming prep single arm lift",
  "fotos": 1
 },
 {
  "id": "pm021",
  "n": "Swimming prep — single leg lift",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica + Unidad externa",
  "obj": "1-Estabilidad Lumbopelvica 2- Unidad Externa SOP",
  "reps": "8–10/lado",
  "musculos": "Glúteo mayor, isquiotibiales, erectores espinales",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de cadera",
  "obs": "No rotar la pelvis.",
  "libro": "Pre-MAT",
  "orig": "Swiming prep single leg lift",
  "fotos": 1
 },
 {
  "id": "pm022",
  "n": "Swimming",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica + Unidad externa",
  "obj": "1-Estabilidad Lumbopelvica 2- Unidad Externa SOP",
  "reps": "8–10 ciclos",
  "musculos": "Erectores espinales, multífidos, glúteos, deltoides posterior",
  "cadena": "Cadena posterior",
  "plano": "Multiplanar",
  "contra": "Dolor lumbar, embarazo",
  "obs": "Movimiento cruzado.",
  "libro": "Pre-MAT",
  "orig": "Swiming",
  "fotos": 1
 },
 {
  "id": "pm023",
  "n": "Opposite single arm lift",
  "pos": "4 puntos",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "Estabilidad Lumbopélvica",
  "reps": "8–10/lado",
  "musculos": "Transverso abdominal, oblicuos, serrato anterior, deltoides",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor de hombro, muñeca",
  "obs": "Pelvis estable.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm024",
  "n": "Opposite single leg lift",
  "pos": "4 puntos",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "Estabilidad Lumbopélvica",
  "reps": "8–10/lado",
  "musculos": "Glúteo mayor, multífidos, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de cadera",
  "obs": "No rotar la pelvis.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm025",
  "n": "Opposite arm and leg reach",
  "pos": "4 puntos",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica + Unidad externa",
  "obj": "Estabilidad Lumbopélvica-Unidad Externa",
  "reps": "8–10/lado",
  "musculos": "Transverso abdominal, multífidos, glúteo mayor, deltoides",
  "cadena": "Cadena cruzada",
  "plano": "Multiplanar",
  "contra": "Dolor lumbar, alteración del equilibrio",
  "obs": "Alcanzar largo.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "cuadrupedia_brazo_pierna"
 },
 {
  "id": "pm026",
  "n": "Standing Diagonal Press",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Unidad externa",
  "obj": "SOP-SOA",
  "reps": "8–10/lado",
  "musculos": "Oblicuos, glúteos, transverso abdominal",
  "cadena": "Cadena cruzada",
  "plano": "Transversal",
  "contra": "Dolor lumbar, embarazo",
  "obs": "Tronco estable.",
  "libro": "Pre-MAT",
  "orig": "Standing diagonal Press",
  "fotos": 1
 },
 {
  "id": "pm027",
  "n": "Standing Marching",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "Estabilidad Lumbopélvica dínámica",
  "reps": "10–20 pasos",
  "musculos": "Psoas, glúteo medio, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Alteración del equilibrio",
  "obs": "Postura erguida.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm028",
  "n": "Walking",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Estabilidad lumbopélvica",
  "obj": "Estabilidad Lumbopélvica dínámica",
  "reps": "10–20 pasos",
  "musculos": "Glúteos, cuádriceps, isquiotibiales, gastrocnemios",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Alteración de la marcha",
  "obs": "Alineación corporal.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm029",
  "n": "Cat Cow",
  "pos": "4 puntos",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Movilizar Columna Dorsal extensión y flexión",
  "reps": "6–10",
  "musculos": "Erectores espinales, recto abdominal, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor agudo de columna",
  "obs": "Movimiento segmentado.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm030",
  "n": "Tail Wag",
  "pos": "4 puntos",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Movilizar Columna Dorsal extensión y flexión",
  "reps": "6–10/lado",
  "musculos": "Oblicuos, multífidos, cuadrado lumbar",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor lumbar agudo",
  "obs": "Movimiento fluido.",
  "libro": "Pre-MAT",
  "revisar": [
   "El objetivo dice extensión y flexión, pero el Tail Wag es flexión lateral (plano frontal)."
  ],
  "fotos": 1
 },
 {
  "id": "pm031",
  "n": "Abdominal Curl",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Fortalecer los abdominales",
  "reps": "8–10",
  "musculos": "Recto abdominal, oblicuos, transverso abdominal",
  "cadena": "Cadena anterior",
  "plano": "Sagital",
  "contra": "Dolor cervical",
  "obs": "Escápulas despegan.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "curl_abdominal"
 },
 {
  "id": "pm032",
  "n": "Oblique Abdominals",
  "pos": "Supino",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "1-Fuerza abdominales 2-Estabilidad Lumbopelvica 3-fuerza del tronco",
  "reps": "8–10/lado",
  "musculos": "Oblicuos, transverso abdominal, recto abdominal",
  "cadena": "Cadena cruzada",
  "plano": "Transversal",
  "contra": "Hernia lumbar, dolor cervical",
  "obs": "Pelvis estable.",
  "libro": "Pre-MAT",
  "orig": "Oblicue abdominals",
  "fotos": 1,
  "parecida": "curl_abdominal"
 },
 {
  "id": "pm033",
  "n": "Rocket",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Fortalecer cadena Posterior y aumentar la extensión Columna",
  "reps": "6–8",
  "musculos": "Erectores espinales, glúteo mayor, isquiotibiales",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar, embarazo",
  "obs": "Brazos atrás, extensión torácica.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "fotoDudosa": "La foto decía \"1. Mini Swan\", pero la fila es Rocket.",
  "parecida": "extension_prona"
 },
 {
  "id": "pm034",
  "n": "Mini Swan",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Extensión de Columna",
  "reps": "5–8 repeticiones",
  "musculos": "Erectores espinales, multífidos, romboides, trapecio inferior",
  "cadena": "Cadena longitudinal posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo, embarazo, cirugía reciente",
  "obs": "Extensión torácica; abdomen activo.",
  "libro": "Pre-MAT",
  "fotos": 2,
  "parecida": "extension_prona"
 },
 {
  "id": "pm035",
  "n": "Swan",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Extensión de Columna",
  "reps": "5–8 repeticiones",
  "musculos": "Erectores espinales, dorsal ancho, glúteo mayor, multífidos",
  "cadena": "Cadena longitudinal posterior",
  "plano": "Sagital",
  "contra": "Embarazo, dolor en extensión, cirugía reciente",
  "obs": "Evitar colapso lumbar.",
  "libro": "Pre-MAT",
  "orig": "Swam",
  "fotos": 1
 },
 {
  "id": "pm036",
  "n": "Seated Side Stretch",
  "pos": "Sedente",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Flexión lateral",
  "reps": "3–5 repeticiones por lado",
  "musculos": "Oblicuos, cuadrado lumbar, intercostales",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor costal, escoliosis dolorosa",
  "obs": "Crecer antes de inclinarse.",
  "libro": "Pre-MAT",
  "orig": "Seated side streth",
  "fotos": 1
 },
 {
  "id": "pm037",
  "n": "Seated Twist",
  "pos": "Sedente",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Rotación Columna",
  "reps": "4–6 repeticiones por lado",
  "musculos": "Oblicuos, multífidos, rotadores profundos",
  "cadena": "Cadena oblicua anterior",
  "plano": "Transversal",
  "contra": "Hernia discal aguda, cirugía abdominal",
  "obs": "Pelvis estable.",
  "libro": "Pre-MAT",
  "orig": "Seated twist",
  "fotos": 1
 },
 {
  "id": "pm038",
  "n": "Standing Roll Down",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Flexión de Columna",
  "reps": "3–5 repeticiones",
  "musculos": "Recto abdominal, oblicuos, erectores espinales",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Osteoporosis severa, vértigo",
  "obs": "Articular la columna.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm039",
  "n": "Standing Flexion",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Flexión de Columna",
  "reps": "5–8 repeticiones",
  "musculos": "Recto abdominal, transverso, oblicuos",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Hernia lumbar aguda",
  "obs": "Iniciar desde el centro.",
  "libro": "Pre-MAT",
  "orig": "Standing Flx",
  "fotos": 1,
  "fotoDudosa": "La foto es la misma que la de Standing Lateral Flexion (dice \"8. Standing Lateral Flexion\")."
 },
 {
  "id": "pm040",
  "n": "Standing Extension",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Extensión de Columna",
  "reps": "5–8 repeticiones",
  "musculos": "Erectores espinales, glúteos, isquiotibiales",
  "cadena": "Cadena longitudinal posterior",
  "plano": "Sagital",
  "contra": "Dolor en extensión, espondilolistesis",
  "obs": "Esternón elevado.",
  "libro": "Pre-MAT",
  "orig": "Standing Extensión",
  "fotos": 1
 },
 {
  "id": "pm041",
  "n": "Standing Lateral Flexion",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Flexión lateral",
  "reps": "3–5 repeticiones por lado",
  "musculos": "Oblicuos, cuadrado lumbar",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor lumbar lateral",
  "obs": "No elevar hombros.",
  "libro": "Pre-MAT",
  "orig": "Standing lateral Flex",
  "fotos": 1
 },
 {
  "id": "pm042",
  "n": "Standing Full Body Rotation",
  "pos": "Bípedo",
  "principio": "Integración del tronco",
  "comp": "Movilidad de la columna",
  "obj": "Rotación Columna",
  "reps": "4–6 repeticiones por lado",
  "musculos": "Oblicuos, glúteos, multífidos",
  "cadena": "Cadena oblicua anterior",
  "plano": "Transversal",
  "contra": "Hernia discal aguda",
  "obs": "Rotar desde los pies.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm043",
  "n": "Marching Supine",
  "pos": "Supino",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Flexión de cadera",
  "obj": "Flexión de cadera supino-Estabilida Lumbopelvica",
  "reps": "8–10 alternando",
  "musculos": "Transverso, psoas, multífidos",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo",
  "obs": "Pelvis neutra.",
  "libro": "Pre-MAT",
  "orig": "Maring Supine",
  "fotos": 1,
  "parecida": "marcha_supina"
 },
 {
  "id": "pm044",
  "n": "Marching Seated",
  "pos": "Sedente (silla)",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Flexión de cadera",
  "obj": "Flexión de cadera-Fortalece el psoas, íliaco-Estabilidad Lumbopelvica vertical",
  "reps": "8–10 alternando",
  "musculos": "Psoas, transverso, erectores espinales",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor de cadera",
  "obs": "Columna erguida.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm045",
  "n": "Marching Standing",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Flexión de cadera",
  "obj": "Entrena equilibrio y coordinación-Flexores cadera-Estabilidad Lumbopelvica",
  "reps": "10–20 alternando",
  "musculos": "Flexores de cadera, glúteo medio, tibial anterior",
  "cadena": "Cadena funcional de la marcha",
  "plano": "Sagital",
  "contra": "Alteración grave del equilibrio",
  "obs": "Tronco estable.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm046",
  "n": "Variación de Swimming",
  "pos": "Prono",
  "principio": "Integración del tronco",
  "comp": "Extensión de cadera",
  "obj": "Extensores de cadera-Isquiotibiales glúteo mayor",
  "reps": "10–20 alternando",
  "musculos": "Espinales, glúteos, isquiotibiales, deltoides posterior",
  "cadena": "Cadena oblicua posterior",
  "plano": "Multiplanar",
  "contra": "Embarazo, dolor lumbar",
  "obs": "Movimiento cruzado.",
  "libro": "Pre-MAT",
  "orig": "Variación swiming",
  "fotos": 1
 },
 {
  "id": "pm047",
  "n": "All fours: extensión de cadera",
  "pos": "4 puntos",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Extensión de cadera",
  "obj": "Extensores de cadera-Moviliza cadera en ext y flx",
  "reps": "6–8 repeticiones",
  "musculos": "Transverso, serrato anterior, multífidos, glúteos",
  "cadena": "Cadena profunda anterior",
  "plano": "Sagital",
  "contra": "Dolor de muñeca, hernia aguda",
  "obs": "Columna neutra.",
  "libro": "Pre-MAT",
  "orig": "All fourextensión o extesión a Flex",
  "fotos": 1,
  "parecida": "cuadrupedia_cadera"
 },
 {
  "id": "pm048",
  "n": "All fours: de flexión a extensión",
  "pos": "4 puntos",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Extensión de cadera",
  "obj": "Extensores de cadera-Equilibrio y Estabilidad lumbopélvica.",
  "reps": "6–10",
  "musculos": "Erectores espinales, recto abdominal, transverso abdominal, multífidos",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor lumbar agudo, lesión de muñeca",
  "obs": "Movimiento segmentado.",
  "libro": "Pre-MAT",
  "orig": "All four Flexion to Extensión",
  "fotos": 1,
  "parecida": "cuadrupedia_cadera"
 },
 {
  "id": "pm049",
  "n": "Abducción dando un paso al costado",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Abducción de cadera",
  "obj": "Abducción de cadera y estabilidad lateral de cadera",
  "reps": "8–10/lado",
  "musculos": "Glúteo medio, glúteo menor, tensor de la fascia lata",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor de cadera, alteración del equilibrio",
  "obs": "Mantener pelvis nivelada.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "paso_lateral"
 },
 {
  "id": "pm050",
  "n": "Levantamiento lateral pierna de pie",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Abducción de cadera",
  "obj": "Abducción de cadera-Cadena cinética cerrada",
  "reps": "8–10/lado",
  "musculos": "Glúteo medio, glúteo menor, tensor de la fascia lata",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor de cadera, inestabilidad",
  "obs": "Tronco vertical.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "paso_lateral"
 },
 {
  "id": "pm051",
  "n": "ABD con paso al lado",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Abducción de cadera",
  "obj": "Abducción de cadera-Estabilidad lateral",
  "reps": "8–10/lado",
  "musculos": "Glúteo medio, glúteo mayor, tensor de la fascia lata",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor de rodilla, alteración del equilibrio",
  "obs": "Paso controlado.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "paso_lateral"
 },
 {
  "id": "pm052",
  "n": "Levantamiento de pierna de pie",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Abducción de cadera",
  "obj": "Equilibrio , coordinación de abdunctores de cadera- Estabiliación Lumbopélvica",
  "reps": "8–10/lado",
  "musculos": "Psoas, recto femoral, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor de cadera, lesión lumbar",
  "obs": "No mover la pelvis.",
  "libro": "Pre-MAT",
  "revisar": [
   "Componente: abducción, pero los músculos (psoas, recto femoral) y el plano sagital corresponden a flexión."
  ],
  "fotos": 1,
  "parecida": "paso_lateral"
 },
 {
  "id": "pm053",
  "n": "Levantamiento de pierna acostado de lado",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Aducción de cadera",
  "obj": "Aductores de cadera",
  "reps": "8–10/lado",
  "musculos": "Glúteo medio, glúteo menor, oblicuos",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor de cadera, bursitis",
  "obs": "Mantener alineación corporal.",
  "libro": "Pre-MAT",
  "revisar": [
   "Componente: aducción, pero los músculos listados (glúteo medio y menor) son abductores."
  ],
  "fotos": 1
 },
 {
  "id": "pm054",
  "n": "Sentado con el aro",
  "pos": "Sedente (silla)",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Aducción de cadera",
  "obj": "Aductores de cadera- Equilibrio-Estabilidad lumpélvica",
  "reps": "8–12",
  "musculos": "Aductores, transverso abdominal, piso pélvico",
  "cadena": "Cadena anterior",
  "plano": "Frontal",
  "contra": "Dolor de rodilla, lesión de cadera",
  "obs": "Presión suave y constante.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm055",
  "n": "Aducción De pie",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Aducción de cadera",
  "obj": "Aductores de cadera- Equilibrio-Estabilidad lumpélvica",
  "reps": "8–10/lado",
  "musculos": "Aductor mayor, aductor largo, transverso abdominal",
  "cadena": "Cadena anterior",
  "plano": "Frontal",
  "contra": "Dolor de cadera, lesión de aductores",
  "obs": "Pelvis estable.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "fotoDudosa": "La foto muestra un ejercicio acostado de lado, pero la fila es Aducción de pie."
 },
 {
  "id": "pm056",
  "n": "Serie de tobillos boca arriba(point flex)",
  "pos": "Supino",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Pies y tobillos",
  "obj": "Fuerza y movilidad tobillo",
  "reps": "10–15",
  "musculos": "Tibial anterior, gastrocnemio, sóleo, peroneos",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión aguda de tobillo",
  "obs": "Movimiento completo.",
  "libro": "Pre-MAT",
  "fotos": 2
 },
 {
  "id": "pm057",
  "n": "Flexión plantar y dorsal en posición sentada",
  "pos": "Sedente",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Pies y tobillos",
  "obj": "Flexión plantar y flexión dorsal",
  "reps": "10–15",
  "musculos": "Tibial anterior, gastrocnemio, sóleo",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión aguda de tobillo",
  "obs": "Movimiento lento y controlado.",
  "libro": "Pre-MAT",
  "fotos": 2
 },
 {
  "id": "pm058",
  "n": "Standing Heel Raise",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Pies y tobillos",
  "obj": "Elevación del talón-Fuerza y movilidad d elos tobillos",
  "reps": "10–15",
  "musculos": "Gastrocnemio, sóleo, tibial posterior, peroneos",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión aguda de tobillo, alteración del equilibrio",
  "obs": "Elevar y bajar con control.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm059",
  "n": "Marcha con movimiento de brazos",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Patrón de movimiento funcional",
  "obj": "Contrarotación del tronco y pelvis-Tronco rota en dirección de pierna levantada",
  "reps": "10–20 pasos",
  "musculos": "Psoas, deltoides, transverso abdominal, glúteo medio",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Multiplanar",
  "contra": "Alteración del equilibrio, dolor de hombro",
  "obs": "Coordinar brazos y piernas.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm060",
  "n": "Sentadilla con flexión de rodillas",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Patrón de movimiento funcional",
  "obj": "Calentar caderas-rodillas y tobillos-Refuerzan glúteos , isquiotibiales - cuadriceps",
  "reps": "8–12",
  "musculos": "Glúteo mayor, cuádriceps, isquiotibiales, transverso abdominal",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor de rodilla, lesión lumbar",
  "obs": "Rodillas alineadas.",
  "libro": "Pre-MAT",
  "orig": "Sendatilla Flexión de rodillas",
  "fotos": 1,
  "parecida": "plie"
 },
 {
  "id": "pm061",
  "n": "Sentadilla con pies hacia afuera ampliado",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Patrón de movimiento funcional",
  "obj": "Calentar caderas-rodillas y tobillos-Refuerzan glúteos , isquiotibiales - cuadriceps",
  "reps": "8–12",
  "musculos": "Glúteo mayor, aductores, cuádriceps, glúteo medio",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión de cadera, dolor de rodilla",
  "obs": "Rodillas siguen la línea de los pies.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm062",
  "n": "Sentadilla estrecha y paralela",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Patrón de movimiento funcional",
  "obj": "",
  "reps": "8–12",
  "musculos": "Cuádriceps, glúteo mayor, isquiotibiales",
  "cadena": "Cadena anterior",
  "plano": "Sagital",
  "contra": "Dolor patelofemoral, lesión de rodilla",
  "obs": "Mantener pelvis neutra.",
  "libro": "Pre-MAT",
  "orig": "Sentadilla estrecha y paralela 90pág",
  "fotos": 1
 },
 {
  "id": "pm063",
  "n": "Estocada",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Patrón de movimiento funcional",
  "obj": "Fuerza y equilibrio y potencia isquiotibiales , glúteo y Cuádriceps",
  "reps": "8–10/lado",
  "musculos": "Glúteo mayor, cuádriceps, isquiotibiales, glúteo medio",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión de rodilla, alteración del equilibrio",
  "obs": "Rodilla sobre el tobillo.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "estocada"
 },
 {
  "id": "pm064",
  "n": "Inclinación zancada hacia adelante",
  "pos": "Bípedo",
  "principio": "Fuerza y potencia de MMII",
  "comp": "Patrón de movimiento funcional",
  "obj": "Fuerza y equilibrio y potencia isquiotibiales , glúteo y Cuádriceps",
  "reps": "8–10/lado",
  "musculos": "Glúteo mayor, isquiotibiales, erectores espinales, transverso abdominal",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de cadera",
  "obs": "Columna larga durante la inclinación.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "estocada"
 },
 {
  "id": "pm065",
  "n": "Rotación lateral del hombro con liga",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad glenohumeral",
  "obj": "Fortalece infraespinoso y redondo menor.",
  "reps": "10–15",
  "musculos": "Infraespinoso, redondo menor, deltoides posterior, manguito rotador",
  "cadena": "Cadena posterior superior",
  "plano": "Transversal",
  "contra": "Lesión aguda de hombro, luxación",
  "obs": "Codos pegados al cuerpo.",
  "libro": "Pre-MAT",
  "orig": "Rotación Lateral del hombro con la liga dira afuera",
  "fotos": 1,
  "parecida": "rotacion_hombro_banda"
 },
 {
  "id": "pm066",
  "n": "Rotación medial del hombro con liga",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad glenohumeral",
  "obj": "Fortalece manguito del rotador",
  "reps": "10–15",
  "musculos": "Subescapular, pectoral mayor, dorsal ancho",
  "cadena": "Cadena anterior superior",
  "plano": "Transversal",
  "contra": "Lesión aguda de hombro, dolor anterior",
  "obs": "Mantener escápulas estables.",
  "libro": "Pre-MAT",
  "orig": "Rotación medial del hombro , roto adentro",
  "fotos": 1,
  "parecida": "rotacion_hombro_banda"
 },
 {
  "id": "pm067",
  "n": "Arm Raises (juntos y alternados)",
  "pos": "Supino",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Ritmo escapular",
  "obj": "Calentamiento suave de la articulación",
  "reps": "8–10",
  "musculos": "Deltoides anterior, serrato anterior, trapecio inferior, transverso abdominal",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Dolor de hombro, pinzamiento subacromial",
  "obs": "Evitar elevar los hombros.",
  "libro": "Pre-MAT",
  "orig": "Arm rais toguether and alternathing",
  "fotos": 2
 },
 {
  "id": "pm068",
  "n": "Angels in the Snow",
  "pos": "Supino",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Ritmo escapular",
  "obj": "Movilidad escapular - Coordina esmipa dorsal , hombro y cabeza",
  "reps": "8–10",
  "musculos": "Trapecio inferior, serrato anterior, deltoides posterior, romboides",
  "cadena": "Cadena posterior superior",
  "plano": "Frontal",
  "contra": "Lesión de hombro, pinzamiento subacromial",
  "obs": "Escápulas estables.",
  "libro": "Pre-MAT",
  "orig": "Angels in the snow",
  "fotos": 2
 },
 {
  "id": "pm069",
  "n": "Telescope Arms",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Ritmo escapular",
  "obj": "Movilidad escapular - Coordina esmipa dorsal , hombro y cabeza",
  "reps": "8–10",
  "musculos": "Deltoides, serrato anterior, trapecio inferior, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor de hombro, lesión cervical",
  "obs": "Alcanzar largo con los brazos.",
  "libro": "Pre-MAT",
  "orig": "Telescope Arme",
  "fotos": 1
 },
 {
  "id": "pm070",
  "n": "Pinwheel",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Ritmo escapular",
  "obj": "Movilidad escapular - Coordina esmipa dorsal , hombro y cabeza",
  "reps": "6–8/lado",
  "musculos": "Oblicuos, erectores espinales, serrato anterior, deltoides",
  "cadena": "Cadena cruzada",
  "plano": "Multiplanar",
  "contra": "Dolor lumbar agudo, vértigo",
  "obs": "Rotación controlada.",
  "libro": "Pre-MAT",
  "orig": "Pinwell",
  "fotos": 2
 },
 {
  "id": "pm071",
  "n": "Single arm lift Plank",
  "pos": "4 puntos",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad y movilidad Escapular",
  "reps": "6–8/lado",
  "musculos": "Transverso abdominal, serrato anterior, deltoides, glúteo medio",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Multiplanar",
  "contra": "Dolor de hombro, lesión de muñeca",
  "obs": "Evitar rotación del tronco.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm072",
  "n": "Sternum Drops",
  "pos": "4 puntos",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad y movilidad Escapular",
  "reps": "8–10",
  "musculos": "Serrato anterior, pectoral menor, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor esternoclavicular",
  "obs": "Movimiento solo escapular.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm073",
  "n": "Modified plank con rodillas extendidas en el suelo",
  "pos": "4 puntos",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad y movilidad Escapular",
  "reps": "20–30 segundos",
  "musculos": "Transverso abdominal, serrato anterior, glúteos, cuádriceps",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de hombro",
  "obs": "Mantener línea corporal.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm074",
  "n": "Tabla Alta brazos",
  "pos": "Plancha prona",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Entrenar todo el cuerpo. Estabilidad Escapular. Mejora postura",
  "reps": "20–30 segundos",
  "musculos": "Transverso abdominal, serrato anterior, deltoides, glúteos",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Lesión de muñeca, dolor lumbar",
  "obs": "Empujar el suelo.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm075",
  "n": "Tabla con pierna levantada",
  "pos": "Plancha prona",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Entrenar todo el cuerpo. Estabilidad Escapular. Mejora postura",
  "reps": "6–8/lado",
  "musculos": "Glúteo mayor, transverso abdominal, serrato anterior, multífidos",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de hombro",
  "obs": "No mover la pelvis.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm076",
  "n": "Tabla en Codos",
  "pos": "Plancha prona",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Entrenar todo el cuerpo. Estabilidad Escapular. Mejora postura",
  "reps": "20–30 segundos",
  "musculos": "Transverso abdominal, recto abdominal, serrato anterior, glúteos",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor de hombro, lesión lumbar",
  "obs": "Mantener cuello neutro.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm077",
  "n": "Tabla con flexión de brazos (sobre las palmas)",
  "pos": "Plancha prona",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Entrenar todo el cuerpo. Estabilidad Escapular. Mejora postura",
  "reps": "6–10",
  "musculos": "Pectoral mayor, tríceps, deltoides anterior, transverso abdominal",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, lesión de muñeca",
  "obs": "Codos cerca del cuerpo.",
  "libro": "Pre-MAT",
  "orig": "Tabla flexón de brazos- Solo las palmas",
  "fotos": 1
 },
 {
  "id": "pm078",
  "n": "Preparación de tabla de espalda: elevación y depresión",
  "pos": "Plancha supina",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad escapular, extesores de espalda y cadera",
  "reps": "8–10",
  "musculos": "Hazme lo mismo o pero con estos ejercicios",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor de muñeca",
  "obs": "Escápulas activas.",
  "libro": "Pre-MAT",
  "orig": "Preparación de la tabla elevacion y depresión de la espalda",
  "revisar": [
   "La columna de músculos tiene un texto que no corresponde (\"Hazme lo mismo o pero con estos ejercicios\")."
  ],
  "fotos": 1,
  "parecida": "tabla_espalda_rodillas"
 },
 {
  "id": "pm079",
  "n": "Tabla de espalda modificada",
  "pos": "Plancha supina",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad escapular, extesores de espalda y cadera",
  "reps": "20–30 segundos",
  "musculos": "Glúteo mayor, tríceps, serrato anterior, isquiotibiales",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor lumbar",
  "obs": "Elevar el esternón.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "tabla_espalda_rodillas"
 },
 {
  "id": "pm080",
  "n": "Marchando con tabla espalda",
  "pos": "Plancha supina",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad escapular, extesores de espalda y cadera",
  "reps": "6–8/lado",
  "musculos": "Glúteo mayor, transverso abdominal, tríceps, serrato anterior",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor lumbar, alteración del equilibrio",
  "obs": "Pelvis estable.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm081",
  "n": "Tabla espalda pierna estirada",
  "pos": "Plancha supina",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad escapular, extesores de espalda y cadera",
  "reps": "6–8/lado",
  "musculos": "Glúteo mayor, isquiotibiales, tríceps, serrato anterior",
  "cadena": "Cadena posterior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor lumbar",
  "obs": "Mantener la altura de la pelvis.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm082",
  "n": "Levantamiento de piernas en tabla de espalda",
  "pos": "Plancha supina",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Estabilidad escapular, extesores de espalda y cadera",
  "reps": "6–8/lado",
  "musculos": "Glúteo mayor, flexores de cadera, tríceps, transverso abdominal",
  "cadena": "Centro estabilizador (Powerhouse)",
  "plano": "Sagital",
  "contra": "Dolor lumbar, lesión de hombro",
  "obs": "No hundir la pelvis.",
  "libro": "Pre-MAT",
  "orig": "Levantamiento de piernas con planca de espalda",
  "fotos": 1
 },
 {
  "id": "pm083",
  "n": "Side plank sube y baja",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Trabaja el tronco lateral. Estabilidad escapular , oblicuos aabductores",
  "reps": "8–10/lado",
  "musculos": "Oblicuos, cuadrado lumbar, glúteo medio, serrato anterior",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor de hombro, lesión lumbar",
  "obs": "Elevar desde la cintura.",
  "libro": "Pre-MAT",
  "fotos": 2
 },
 {
  "id": "pm084",
  "n": "Tabla lateral antebrazo",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Trabaja el tronco lateral. Estabilidad escapular , oblicuos aabductores",
  "reps": "20–30 segundos",
  "musculos": "Oblicuos, glúteo medio, serrato anterior, cuadrado lumbar",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Lesión de hombro, alteración del equilibrio",
  "obs": "Mantener alineación corporal.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "tabla_lateral"
 },
 {
  "id": "pm085",
  "n": "Prep tabla lateral",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Trabaja el tronco lateral. Estabilidad escapular , oblicuos aabductores",
  "reps": "20–30 segundos",
  "musculos": "Oblicuos, glúteo medio, serrato anterior",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Dolor de hombro, lesión lumbar",
  "obs": "Apoyar correctamente el antebrazo.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm086",
  "n": "Tabla lateral con los pie uno sobre otro",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Trabaja el tronco lateral. Estabilidad escapular , oblicuos aabductores",
  "reps": "20–30 segundos",
  "musculos": "Oblicuos, glúteo medio, serrato anterior, aductores",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Lesión de hombro, dolor lumbar",
  "obs": "Cuerpo en línea recta.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "tabla_lateral"
 },
 {
  "id": "pm087",
  "n": "Levantamiento de la pierna en tabla lateral",
  "pos": "Decúbito lateral",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Estabilidad escapular (planchas)",
  "obj": "Trabaja el tronco lateral. Estabilidad escapular , oblicuos aabductores",
  "reps": "6–8/lado",
  "musculos": "Glúteo medio, glúteo menor, oblicuos, serrato anterior",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Alteración del equilibrio, lesión de cadera",
  "obs": "Evitar caída de la pelvis.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm088",
  "n": "Remo con bandas",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro posterior",
  "obj": "Movimiento funcionales y activación del hombro",
  "reps": "8–12",
  "musculos": "Dorsal ancho, romboides, trapecio medio, bíceps",
  "cadena": "Cadena posterior superior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor cervical",
  "obs": "Escápulas hacia atrás.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "banda_inclinada"
 },
 {
  "id": "pm089",
  "n": "Prensa de tríceps con banda (tiro atrás)",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro posterior",
  "obj": "Movimiento funcionales y activación del hombro",
  "reps": "8–12",
  "musculos": "Tríceps braquial, deltoides posterior, serrato anterior",
  "cadena": "Cadena posterior superior",
  "plano": "Sagital",
  "contra": "Lesión de codo, dolor de hombro",
  "obs": "Codos pegados al cuerpo.",
  "libro": "Pre-MAT",
  "orig": "Prensa de Triceps con banda. Tiro atrás",
  "fotos": 2,
  "parecida": "banda_inclinada"
 },
 {
  "id": "pm090",
  "n": "Inmersión de tríceps (banca o silla)",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro posterior",
  "obj": "Movimiento funcionales y activación del hombro",
  "reps": "6–10",
  "musculos": "Tríceps braquial, deltoides anterior, pectoral mayor",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor de muñeca",
  "obs": "Hombros alejados de las orejas.",
  "libro": "Pre-MAT",
  "orig": "Inmersión de triceps. Bnaca o silla pilates",
  "fotos": 2
 },
 {
  "id": "pm091",
  "n": "Prensa por encima de la cabeza con banda",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro posterior",
  "obj": "Movimiento funcionales y activación del hombro",
  "reps": "8–12",
  "musculos": "Deltoides, tríceps, trapecio superior",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Pinzamiento de hombro, lesión cervical",
  "obs": "No elevar los hombros.",
  "libro": "Pre-MAT",
  "orig": "Presna por encima de la cabeza , con banda",
  "fotos": 1
 },
 {
  "id": "pm092",
  "n": "Prensa lateral con la banda",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro posterior",
  "obj": "Movimiento funcionales y activación del hombro",
  "reps": "8–12/lado",
  "musculos": "Deltoides medio, serrato anterior, oblicuos",
  "cadena": "Cadena lateral",
  "plano": "Frontal",
  "contra": "Lesión de hombro",
  "obs": "Tronco estable.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "banda_pecho"
 },
 {
  "id": "pm093",
  "n": "Tirón hacia abajo con banda",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro posterior",
  "obj": "Movimiento funcionales y activación del hombro",
  "reps": "8–12",
  "musculos": "Dorsal ancho, trapecio inferior, romboides",
  "cadena": "Cadena posterior superior",
  "plano": "Frontal",
  "contra": "Lesión de hombro",
  "obs": "Escápulas descienden.",
  "libro": "Pre-MAT",
  "orig": "Tirando hacia abajo banda abre la banda arriba y abajo",
  "fotos": 1,
  "parecida": "banda_pecho"
 },
 {
  "id": "pm094",
  "n": "Prensa de pecho con banda",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro anterior",
  "obj": "Felxion de bíceps-hombro",
  "reps": "8–12",
  "musculos": "Pectoral mayor, tríceps, deltoides anterior",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor pectoral",
  "obs": "Costillas conectadas.",
  "libro": "Pre-MAT",
  "fotos": 1,
  "parecida": "banda_pecho"
 },
 {
  "id": "pm095",
  "n": "Flexión de bíceps con banda",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Activación del hombro anterior",
  "obj": "Felxion de bíceps-hombro",
  "reps": "8–12",
  "musculos": "Bíceps braquial, braquial, braquiorradial",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Tendinitis de bíceps, lesión de codo",
  "obs": "Codos fijos.",
  "libro": "Pre-MAT",
  "orig": "Flexión de bíceps de cualquier ángulo. Con banda con apoyo de pies",
  "fotos": 1
 },
 {
  "id": "pm096",
  "n": "Elevación hacia adelante con banda y sentadilla",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Movimiento del brazo recto",
  "obj": "Aumenta carga para el hombro y fuerza MMSS",
  "reps": "8–10",
  "musculos": "Deltoides anterior, cuádriceps, glúteos, transverso abdominal",
  "cadena": "Cadena cruzada",
  "plano": "Multiplanar",
  "contra": "Dolor de hombro, lesión de rodilla",
  "obs": "Coordinar brazos y piernas.",
  "libro": "Pre-MAT",
  "fotos": 1
 },
 {
  "id": "pm097",
  "n": "Elevación Lateral de Brazos",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Movimiento del brazo recto",
  "obj": "Aumenta carga para el hombro y fuerza MMSS",
  "reps": "8–10",
  "musculos": "Deltoides anterior, serrato anterior, trapecio inferior",
  "cadena": "Cadena anterior superior",
  "plano": "Sagital",
  "contra": "Pinzamiento subacromial",
  "obs": "Brazos largos, hombros bajos.",
  "libro": "Pre-MAT",
  "revisar": [
   "Una elevación lateral de brazos ocurre en el plano frontal (deltoides medio), no en el sagital."
  ],
  "fotos": 1
 },
 {
  "id": "pm098",
  "n": "Tirar los brazos hacia atrás con liga",
  "pos": "Bípedo",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Movimiento del brazo recto",
  "obj": "Aumenta carga para el hombro y fuerza MMSS",
  "reps": "8–12",
  "musculos": "Dorsal ancho, romboides, trapecio medio, deltoides posterior",
  "cadena": "Cadena posterior superior",
  "plano": "Sagital",
  "contra": "Lesión de hombro, dolor cervical",
  "obs": "Escápulas hacia atrás.",
  "libro": "Pre-MAT",
  "orig": "Tirar hacia atrás los brazos atrás con una liga",
  "fotos": 1,
  "parecida": "banda_inclinada"
 },
 {
  "id": "pm099",
  "n": "Movimiento de rotación con resistencia",
  "pos": "De rodillas",
  "principio": "Fuerza y equilibrio de MMSS",
  "comp": "Movimiento de todo el cuerpo",
  "obj": "Mover un objeto rotando todo el cuerpo , con un liga o resistencia",
  "reps": "8–10/lado",
  "musculos": "Oblicuos, transverso abdominal, multífidos, deltoides",
  "cadena": "Cadena cruzada",
  "plano": "Transversal",
  "contra": "Hernia discal aguda, dolor lumbar",
  "obs": "Rotar desde el tronco.",
  "libro": "Pre-MAT",
  "fotos": 2
 }
];
